<a href="https://colab.research.google.com/github/freyebeans/ASU-assignments/blob/main/MAT422/HW1.3/notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MAT422 Section 1.3 Linear Regression
Michael Bishop

In [60]:
import numpy as np
import matplotlib.pyplot as plt

np.set_printoptions(precision=4, suppress=True)

## 1.3.1 QR Decomposition
Provided a matrix *A* we can find a matrix with orthonormal columns *Q* and a upper triangular matrix *R* such that *A*=*QR*. The proccess of finding these matrices is called QR decomposition.

In [61]:
A = np.array([[1,0],[1,2],[1,4],[1,6],[1,8]])

Q, R = np.linalg.qr(A)

print("A =")
print(A)
print("Q =")
print(Q)
print("R =")
print(R)
print("Q.T * Q")
print(Q.T @ Q)
print("does Q have orthonormal columns?",np.allclose(Q.T @ Q, np.eye(Q.shape[1])))
print("Q * R")
QR = Q @ R
print(QR)
print("does QR = A?",np.allclose(QR, A))

A =
[[1 0]
 [1 2]
 [1 4]
 [1 6]
 [1 8]]
Q =
[[-0.4472 -0.6325]
 [-0.4472 -0.3162]
 [-0.4472  0.    ]
 [-0.4472  0.3162]
 [-0.4472  0.6325]]
R =
[[-2.2361 -8.9443]
 [ 0.      6.3246]]
Q.T * Q
[[ 1. -0.]
 [-0.  1.]]
does Q have orthonormal columns? True
Q * R
[[ 1. -0.]
 [ 1.  2.]
 [ 1.  4.]
 [ 1.  6.]
 [ 1.  8.]]
does QR = A? True


As you can see *A*=*QR* is true and matrix *Q* has orthonormal columns. 
## 1.3.2 Least-Squares Problems


In [65]:
b = np.array([-0.1,1.1,1.8,3.2,4.1])

x_lstsq, residual_sum, rank, values = np.linalg.lstsq(A,b)
residual = b - A @ x_lstsq

print("least-squares solution from np.linalg.lstsq(A,b)", x_lstsq)
print("residual (b - Ax) =", residual)
print("norm of residual =", np.linalg.norm(residual))
print("rank of A =",np.linalg.matrix_rank(A))
print("sigular values =", values)
print("noraml-equation check A.T * residual =",A.T @ residual)

least-squares solution from np.linalg.lstsq(A,b) [-0.08   0.525]
residual (b - Ax) = [-0.02  0.13 -0.22  0.13 -0.02]
norm of residual = 0.28809720581775894
rank of A = 2
sigular values = [11.1076  1.2732]
noraml-equation check A.T * residual = [ 0. -0.]


In [ ]:
QTb = Q.T @ b
x_qr = np.linalg.solve(R,QTb)
qr_residual = b - A @ x_qr

print("Q.T * b =",QTb)
print("least-squares solution from QR decomposition", x_qr)
print("norm of residual =", np.linalg.norm(qr_residual))

print("\ndoes the QR decomposition solution match the np.linalg.lstsq() solution?",np.allclose(x_qr, x_lstsq))

Q.T * b = [-4.5169  3.3204]
least-squares solution from QR decomposition [-0.08   0.525]
norm of residual = 0.28809720581775866

does the QR decomposition solution match the np.linalg.lstsq() solution? True



## 1.3.3 Linear Regression


In [72]:
x = np.array([0,1,2,3,4,5])
y = np.array([1.9,3.6,5.1,6.3,8.2,9.4])

X = np.column_stack([np.ones_like(x),x])
beta, *_ = np.linalg.lstsq(X, y)
predicted_y = X @ beta
residuals = y - predicted_y
rmse = np.sqrt(np.mean(residuals**2))

print("design matrix X =")
print(X)
print("y intercept (beta_0) =", beta[0])
print("slope (beta_1) =", beta[1])
print("predicted y =", predicted_y)
print("residuals =", residuals)
print("RMSE (root mean square error) =", rmse)

design matrix X =
[[1 0]
 [1 1]
 [1 2]
 [1 3]
 [1 4]
 [1 5]]
y intercept (beta_0) = 2.0000000000000013
slope (beta_1) = 1.4999999999999998
predicted y = [2.  3.5 5.  6.5 8.  9.5]
residuals = [-0.1  0.1  0.1 -0.2  0.2 -0.1]
RMSE (root mean square error) = 0.14142135623730925
